### ISSUE TITLE
Allow restricting lower bound of version

### ISSUE THREAD

**Issue by kyldvs** [gabriel-dehan/dyson-sphere-blueprints#1]
In particular I uploaded with 2.1.4 selected, on the website it shows that 2.1.0-2.1.4 is valid. I would like to set 2.1.1 as a minimum because I use elevated belts and belt-to-belt inserters which do not work in 2.1.0.

Awesome work on the website in general, it's super polished for how fast it was put up :)

**Comment by gabriel-dehan** [comment]
Hey Kyle, thanks for the compliment, that's very nice!

That's a very interesting point you are raising... Currently the "minimum" - "maximum" range is handled automatically when a mod version is flagged as "breaking" (the blueprint format changes) and I am not sure how adding exceptions to that system should work. Currently the blueprint creation form is already a bit complex and adding a field to "override the minimum version" for a very few specific cases might just confuse 99% of the users.
I'll have to think about it but if you have any suggestions on that front please hit me with that. In the meantime you can just add this information to the description of the blueprint, in bold or even as a header in the wysiwig :D

**Comment by kyldvs** [comment]
Yeah that sounds reasonable, I will just add this in the description. I think you're probably right that exceptions like this will be more confusion than they are worth in the long run
