### ISSUE TITLE
This blueprint requires fill option.

### ISSUE THREAD

**Issue by randycarrero** [gabriel-dehan/dyson-sphere-blueprints#14]
instead of having the system search for the requirements have it in the submission form. 

requires to have:
Mass Construction tier 1 [60 Facilities]
Mass Construction tier 2 [150 Facilities]
Mass Construction tier 3 [600 Facilities]
Mass Construction tier 4 [3000 Facilities]
Mass Construction tier 5 [unlimited Facilities]
MultiMod [Stable]
MultiModbeta [Beta  ver.]

Edit:  have it as a new addition to help. I can see how it works in the old one and that is really good feature to have.

**Comment by gabriel-dehan** [comment]
Thanks for the issue (and the PR, I'll look at it later)! This is definitely needed and is planned :)

**Comment by randycarrero** [comment]
No problem glad I could help. I love the site and would like to continue to help as much as I can.
