### ISSUE TITLE
Total Number of entities

### ISSUE THREAD

**Issue by Archangel33** [gabriel-dehan/dyson-sphere-blueprints#16]
It would be really useful to have the total number of entities to be able to tell what tech level of the blueprints tech each blueprint can be used. As well as possibly a sort by/ tag for blueprint tech level.

**Comment by gabriel-dehan** [comment]
Yup, definitely agree and you will have this information, just need to find the time to to do it :)

**Comment by gabriel-dehan** [comment]
I juste pushed a new update with the number of entities added to a blueprint's page. Next step will be to be able to filter / sort blueprints according to that, should be able to do it soon.

**Comment by gabriel-dehan** [comment]
Added the filter by max number of structures :)
