### ISSUE TITLE
Add mods to seed file

### ISSUE THREAD

**Issue by LRFalk01** [gabriel-dehan/dyson-sphere-blueprints#18]
One of the larger barriers to entry in spinning up this code base is the lack of seeded mods. One has to kind of guess what to put into the json value of the table. It would be really helpful to have the values seeded.

Edit:
On second thought ... I don't know if this table is even going to exist in the future with the line items to remove support for mods. Maybe that needs discussed first.

**Comment by gabriel-dehan** [comment]
Hey, thanks for the suggestion, I haven't taken the time to document anything for contributors, I actually didn't expect people to like it or contribute at all ahah, also I developped the whole project in like 4 days or something so it wasn't super thought out.
I intend to have the website be "backward compatible" so I won't remove old blueprints that depended on the mods. The table will stay and we'll only have one mod which is "Dyson Sphere Blueprint". You are totally right about the JSON version not being documented and not being clear at all.

I'll update the doc at some point, in the meantime I'll just send you what it looks like right now on the prod database.
