### ISSUE TITLE
Password recovery?

### ISSUE THREAD

**Issue by Mirco1502** [gabriel-dehan/dyson-sphere-blueprints#23]
Hello,

forgot my password and it seems like there is no button for password recovery? How can I reset my password? :)

Regards

**Comment by Mirco1502** [comment]
I still hope for an answer, because I want to upload my BP's I created yesterday, but like said currently unable to login.

Regards

**Comment by gabriel-dehan** [comment]
Hey add me on discord (Allile [Diacred]#0024) or PM on reddit with your email and I'll reset it for you, but I definitely need to implement the password recovery :p

**Comment by Mirco1502** [comment]
Hello again, thank for the reset, login works now. But sadly I can't see any option to change the pw as you mentioned in your PM?

Thanks so far and Regards

**Comment by Mirco1502** [comment]
Thank you for your support! It's working now! Have a nice day!  (And don't forget to add the password recovery feature :D )

Regards
