### ISSUE TITLE
Server Costs

### ISSUE THREAD

**Issue by LRFalk01** [gabriel-dehan/dyson-sphere-blueprints#34]
I saw a post were you were talking about server costs being a problem. You could significantly lower your costs by making it so that you only retrieve the blueprint when specifically requested. so the blueprint is not requested in the pages or when loading the detail page. it is only requested on a user action specifically requesting to copy it. If you'd like I can work on a PR for this, although I am not a FE engineer. If you are not interested, just close the issue.

**Comment by gabriel-dehan** [comment]
Hey @LRFalk01 , thanks for the suggestion, definitely something I could try doing, and probably will, we already have a version of that for longer blueprint and it'd probably be quite easy to implement everywhere else with a few tweaks.

Haven't had (taken?) the time to do any significant update to DSB recently but when I do I'll try to implement something like that (and also improve the caching, that might help :p)

**Comment by kris44dad** [comment]
You might consider a Patreon page to accept donations, if not already mentioned.

**Comment by gabriel-dehan** [comment]
@kris44dad Thanks for the suggestion but I already have one :) All available sponsor links are on the page : https://www.dysonsphereblueprints.com/supportus

**Comment by gabriel-dehan** [comment]
Done
