### ISSUE TITLE
Counter for the number of times the blueprint was copied

### ISSUE THREAD

**Issue by filadog** [gabriel-dehan/dyson-sphere-blueprints#38]
Awesome site, thank you for all the work! As a blueprint creator I have a small suggestion: simple counter for the number of times each blueprint was copied. I know, I know - fake internet points, but still I think it wouldn't hurt. Some sort of simple IP check would hopefully prevent abuse.

**Comment by gabriel-dehan** [comment]
Hey @filadog !
Thanks for the suggestion :) 

Already got a related issue, definitely is something I'd like to introduce at some point but I am a bit worried about the performance cost of adding so many requests "on read" when the servers are already struggling
https://github.com/gabriel-dehan/dyson-sphere-blueprints/issues/12

**Comment by gabriel-dehan** [comment]
Hey @filadog, the feature is live as of now :)
