### ISSUE TITLE
I want to build a mirror site (China), but I don't know how to use Ruby. Can this site be converted to PHP?

### ISSUE THREAD

**Issue by 122474363** [gabriel-dehan/dyson-sphere-blueprints#41]
I want to build a mirror site (China), but I don't know how to use Ruby. Can this site be converted to PHP?

**Comment by gabriel-dehan** [comment]
Nope, it is impossible to convert a Rails site to PHP, you have to redevelop it. Sorry.
I am considering adding a chinese localisation to the site at some point, just haven't had the time to get to it.

Cheers.
