### ISSUE TITLE
Reforming refine not recognized as a new reciepe...yet.

### ISSUE THREAD

**Issue by kris44dad** [gabriel-dehan/dyson-sphere-blueprints#48]
Refineries using the new Reforming refine reciepe are displayed in the blueprint page as a cog (unassigned reciepe), even when assigned properly. Obvious behavior, if the reciepe hasn't been added yet.

Example:
https://www.dysonsphereblueprints.com/blueprints/factory-consolidated-series-refined-oil-2700-min-hydrogen-neutral

**Comment by Martin-Pitt** [comment]
Have added a PR in #57 which addresses the addition in the data at least
