### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by ar1810** [gabriel-dehan/dyson-sphere-blueprints#7]
Wouldn't be great if you can leave a comment in the bp? to let know the creator of the bp if you made a mistake or simple it's a great bp!

**Comment by gabriel-dehan** [comment]
As I've said on reddit and Discord, I am not comfortable adding comments, it usually means you have to moderate comments, prevent spam, etc... Which is work that I don't want to have to be doing. I am still considering it though

**Comment by mrlunk** [comment]
> t usually means you have to moderate comments, prevent spam, etc...

Is there no way to automate that work with up and downvotes for comments ?

Loving your website btw ;)
Thanks for all the efforts !

PL.

**Comment by afilina** [comment]
What about adding something off-the-shelf like Disqus, and adding a few trusted site members as moderators? Let the community shape the guidelines too via PRs to this repo.

**Comment by gabriel-dehan** [comment]
Will probably implement a simple contact form in-site as a way to contact a blueprints author.
I'll keep just one thread on the subject: https://github.com/gabriel-dehan/dyson-sphere-blueprints/issues/15
