### ISSUE TITLE
The offical blueprints are out

### ISSUE THREAD

**Issue by Suyashtnt** [gabriel-dehan/dyson-sphere-blueprints#9]
Time to get working :)

**Comment by gabriel-dehan** [comment]
Ahahah, will do, not sure when it'll be out though, I have a lot of work atm and probably won't be able to do that before mid week next week if I can't finish it todya

**Comment by gabriel-dehan** [comment]
It's up ;) 

Although you won't have some features and there may be bugs. Preview is not working and blueprint analysis is not working either. Not sure if the blueprint preview will ever come back but the blueprint analysis will be back in the coming weeks :)
